setLocal('0.0.0.0:53')
controlSocket('0.0.0.0:8084')
setKey('d4nspV9KjEcTvnVVfDW38W0crzCu8LQJUmSewFsI/AY=')
addConsoleACL('172.20.0.0/24')
includeDirectory('/etc/dnsdist/conf.d/')
setACL('0.0.0.0/0')
