[tool.poetry]
name = "MultiDirectory"
version = "2.0.0"
description = ""
authors = ["Mastermind-U <rex49513@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "3.12.6"
asn1 = "^2.7.1"
pydantic = {version = "2.3", extras = ["email"]}
loguru = "^0.6.0"
pytz = "^2022.7.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.16"
asyncstdlib = "^3.10.6"
ldap-filter = "^0.2.2"
pydantic-settings = "^2.0.3"
websockets = "^11.0.3"
alembic = "^1.12.1"
ldap3 = "^2.9.1"
bcrypt = "4.0.1"
jinja2 = "^3.1.4"
uvicorn = "^0.30.0"
dishka = "^1.2.0"
uvloop = "^0.19.0"
sqlalchemy = {version = "1.4.54", extras = ["asyncio", "mypy"]}
asyncpg = "^0.29.0"
httpx = "^0.27.2"
fastapi = "^0.115.0"

[tool.poetry.group.linters.dependencies]
flake8-pytest = "^1.4"
flake8-docstrings = "^1.6.0"
flake8 = "5.0.4"
flake8-awesome = "^1.3.0"
types-pytz = "^2022.7.1.0"
mypy = "1.10.1"
ruff = "0.6.3"
flake8-commas = "^4.0.0"
flake8-isort = "^6.1.1"
isort = "^5.13.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.1.0"
gevent = "^23.9.1"
coverage = "7.3.4"
pytest-asyncio = "^0.21.1"


[tool.poetry.group.dev.dependencies]
py-hot-reload = "^1.0.6"
watchdog = "4.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = [
    "ldap_protocol",
    "client",
    "config",
    "models",
    "api",
    "security",
    "tests",
    "web_app",
    "ioc",
    "schedule",
    "extra",
]
include_trailing_comma = true
line_length = 79
multi_line_output = 3

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]
ignore_missing_imports = true
platform = "linux"
disallow_untyped_defs = true
exclude = ["app/alembic", "alembic"]
show_column_numbers = true
pretty = true
warn_unreachable = true
color_output = true
warn_unused_ignores = true

[tool.pytest.ini_options]
pythonpath = ["app"]
addopts = [
    "--cov",
    "--cov-report=xml:coverage.xml",
    "--cov-report=html",
    "--cov-report=term-missing:skip-covered"
]
asyncio_mode = "auto"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
concurrency = ["thread", "gevent"]


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 79
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
