[tool.poetry]
name = "multi-directory"
version = "0.9.0"
description = ""
authors = ["Mastermind-U <rex49513@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = {extras = ["asyncio", "mypy"], version = "^1.4.44"}
asyncpg = "^0.27.0"
alembic = "^1.8.1"
asn1 = "^2.6.0"
pydantic = {extras = ["email"], version = "^1.10.8"}
loguru = "^0.6.0"
sqlalchemy-utils = "^0.38.3"
pytz = "^2022.7.1"
fastapi = "^0.95.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
uvicorn = "^0.21.1"
python-multipart = "^0.0.6"
asyncstdlib = "^3.10.6"
ldap-filter = "^0.2.2"

[tool.poetry.group.linters.dependencies]
mypy = "^0.991"
flake8-pytest = "^1.4"
flake8-docstrings = "^1.6.0"
flake8-commas = "^2.1.0"
isort = "^5.11.3"
flake8 = "5.0.4"
flake8-awesome = "^1.3.0"
types-pytz = "^2022.7.1.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
ldap3 = "^2.9.1"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = ["ldap", "client", "config", "models", "api", "security"]
include_trailing_comma = true
line_length = 79
multi_line_output = 3

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]

[tool.pytest.ini_options]
pythonpath = ["/app"]
