[tool.poetry]
name = "MultiDirectory"
version = "1.12.2"
description = ""
authors = ["Mastermind-U <rex49513@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = {extras = ["asyncio", "mypy"], version = "^1.4.44"}
asyncpg = "^0.27.0"
asn1 = "^2.6.0"
pydantic = {version = "2.3", extras = ["email"]}
loguru = "^0.6.0"
pytz = "^2022.7.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
asyncstdlib = "^3.10.6"
ldap-filter = "^0.2.2"
httpx = "^0.25.0"
fastapi = "^0.103.1"
pydantic-settings = "^2.0.3"
uvloop = "^0.17.0"
websockets = "^11.0.3"
alembic = "^1.12.1"
ldap3 = "^2.9.1"
bcrypt = "4.0.1"
jinja2 = "^3.1.4"
uvicorn = "^0.30.0"

[tool.poetry.group.linters.dependencies]
flake8-pytest = "^1.4"
flake8-docstrings = "^1.6.0"
flake8-commas = "^2.1.0"
isort = "^5.11.3"
flake8 = "5.0.4"
flake8-awesome = "^1.3.0"
types-pytz = "^2022.7.1.0"
mypy = "^1.8.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.1.0"
gevent = "^23.9.1"
coverage = "7.3.4"
pytest-asyncio = "^0.21.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = ["ldap_protocol", "client", "config", "models", "api", "security", "tests"]
include_trailing_comma = true
line_length = 79
multi_line_output = 3

[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]
ignore_missing_imports = true
platform = "linux"
disallow_untyped_defs = true
exclude = "app/alembic"
show_column_numbers = true
pretty = true
warn_unreachable = true
color_output = true
warn_unused_ignores = true

[tool.pytest.ini_options]
pythonpath = ["/app"]
addopts = [
    "--cov",
    "--cov-report=xml:coverage.xml",
    "--cov-report=html",
    "--cov-report=term-missing:skip-covered"
]
asyncio_mode = "auto"

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
concurrency = ["thread", "gevent"]
