"""init

Revision ID: 93d18fa59534
Revises: 
Create Date: 2022-12-08 06:58:47.006912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d18fa59534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=True),
    sa.Column('objectClass', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('whenCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('whenChanged', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Directories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parentId', 'name', name='name_parent_uc')
    )
    op.create_index(op.f('ix_Directories_parentId'), 'Directories', ['parentId'], unique=False)
    op.create_table('Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Settings_name'), 'Settings', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Settings_name'), table_name='Settings')
    op.drop_table('Settings')
    op.drop_index(op.f('ix_Directories_parentId'), table_name='Directories')
    op.drop_table('Directories')
    # ### end Alembic commands ###
