"""Create Access Policies.

Revision ID: 0bf9ba472037
Revises: 9356ff164d89
Create Date: 2024-08-13 08:36:38.851530

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0bf9ba472037'
down_revision = '9356ff164d89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'AccessPolicies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('can_read', sa.Boolean(), nullable=False),
        sa.Column('can_add', sa.Boolean(), nullable=False),
        sa.Column('can_modify', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'AccessPolicyMemberships',
        sa.Column('dir_id', sa.Integer(), nullable=False),
        sa.Column('policy_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['dir_id'], ['Directory.id']),
        sa.ForeignKeyConstraint(['policy_id'], ['AccessPolicies.id']),
        sa.PrimaryKeyConstraint('dir_id', 'policy_id'),
    )
    op.create_table(
        'GroupAccessPolicyMemberships',
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('policy_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['Groups.id']),
        sa.ForeignKeyConstraint(['policy_id'], ['AccessPolicies.id']),
        sa.PrimaryKeyConstraint('group_id', 'policy_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GroupAccessPolicyMemberships')
    op.drop_table('AccessPolicyMemberships')
    op.drop_table('AccessPolicies')
    # ### end Alembic commands ###
