"""empty message.

Revision ID: 1b71cafba681
Revises: 708b01eaf025
Create Date: 2026-03-24 16:28:49.116712

"""

import sqlalchemy as sa
from alembic import op
from dishka import AsyncContainer

# revision identifiers, used by Alembic.
revision: None | str = "1b71cafba681"
down_revision: None | str = "708b01eaf025"
branch_labels: None | list[str] = None
depends_on: None | list[str] = None


def upgrade(container: AsyncContainer) -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "AccessControlEntries",
        sa.Column("attribute_type_name", sa.String(), nullable=False),
    )
    op.execute(
        sa.text(
            """
            UPDATE "AccessControlEntries" AS ace
            SET attribute_type_name = at.name
            FROM "AttributeTypes" AS at
            WHERE ace."attributeTypeId" = at.id
            """,
        ),
    )
    # op.drop_index(
    #     op.f("idx_ace_attribute_type_id"),
    #     table_name="AccessControlEntries",
    #     postgresql_using="hash",
    # )
    # op.drop_constraint(
    #     op.f("AccessControlEntries_directoryAttributeTypeId_fkey"),
    #     "AccessControlEntries",
    #     type_="foreignkey",
    # )
    # op.drop_column("AccessControlEntries", "attributeTypeId")
    # ### end Alembic commands ###


def downgrade(container: AsyncContainer) -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "AccessControlEntries",
    #     sa.Column(
    #         "attributeTypeId",
    #         sa.INTEGER(),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    # )
    op.execute(
        sa.text(
            """
            UPDATE "AccessControlEntries" AS ace
            SET "attributeTypeId" = at.id
            FROM "AttributeTypes" AS at
            WHERE ace.attribute_type_name = at.name
            """,
        ),
    )
    # op.create_foreign_key(
    #     op.f("AccessControlEntries_directoryAttributeTypeId_fkey"),
    #     "AccessControlEntries",
    #     "Directory",
    #     ["attributeTypeId"],
    #     ["id"],
    #     ondelete="CASCADE",
    # )
    # op.create_index(
    #     op.f("idx_ace_attribute_type_id"),
    #     "AccessControlEntries",
    #     ["attributeTypeId"],
    #     unique=False,
    #     postgresql_using="hash",
    # )
    op.drop_column("AccessControlEntries", "attribute_type_name")
    # ### end Alembic commands ###
