"""Add user api roles.

Revision ID: 4461a62bc9d5
Revises: 6303f5c706ec
Create Date: 2025-11-07 15:15:36.727549

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: None | str = "4461a62bc9d5"
down_revision: None | str = "6303f5c706ec"
branch_labels: None | list[str] = None
depends_on: None | list[str] = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserApiPermissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "permissions",
            postgresql.ARRAY(sa.String()),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "permissions"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserApiPermissions")
    # ### end Alembic commands ###
