"""Add user api roles.

Revision ID: 4461a62bc9d5
Revises: 6303f5c706ec
Create Date: 2025-11-07 15:15:36.727549

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: None | str = "4461a62bc9d5"
down_revision: None | str = "6303f5c706ec"
branch_labels: None | list[str] = None
depends_on: None | list[str] = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserApiPermissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "permissions",
            postgresql.ARRAY(
                sa.Enum(
                    "PASSWORD_POLICY_GET_ALL",
                    "PASSWORD_POLICY_GET",
                    "PASSWORD_POLICY_GET_BY_DIR",
                    "PASSWORD_POLICY_UPDATE",
                    "PASSWORD_POLICY_RESET_DOMAIN_POLICY",
                    "PASSWORD_POLICY_TURNOFF",
                    "NETWORK_POLICY_CREATE",
                    "NETWORK_POLICY_GET_LIST_POLICIES",
                    "NETWORK_POLICY_DELETE",
                    "NETWORK_POLICY_SWITCH_NETWORK_POLICY",
                    "NETWORK_POLICY_SWAP_PRIORITIES",
                    "NETWORK_POLICY_UPDATE",
                    name="apipermissions",
                ),
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["id"], ["Users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("UserApiPermissions")
    # ### end Alembic commands ###
