"""empty message.

Revision ID: 552b4eafb1aa
Revises: 2dadf40c026a
Create Date: 2026-02-17 09:24:57.906080

"""

from dishka import AsyncContainer

# revision identifiers, used by Alembic.
revision: None | str = "552b4eafb1aa"
down_revision: None | str = "2dadf40c026a"
branch_labels: None | list[str] = None
depends_on: None | list[str] = None


def upgrade(container: AsyncContainer) -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade(container: AsyncContainer) -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
