"""empty message

Revision ID: 5cf15f0c2696
Revises: d5272e9889c5
Create Date: 2023-09-19 13:18:24.920575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cf15f0c2696'
down_revision = 'd5272e9889c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('netmasks', postgresql.ARRAY(postgresql.CIDR()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('priority')
    )
    op.create_index(op.f('ix_Policies_netmasks'), 'Policies', ['netmasks'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Policies_netmasks'), table_name='Policies')
    op.drop_table('Policies')
    # ### end Alembic commands ###
