"""Merge migrations alembic head.

Revision ID: 692ae64e0cc5
Revises: 4334e2e871a4
Create Date: 2025-02-24 10:46:08.830692

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "692ae64e0cc5"
down_revision = "4334e2e871a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "group_policy_uc",
        "GroupAccessPolicyMemberships",
        ["group_id", "policy_id"],
    )

    op.add_column(
        "Policies",
        sa.Column(
            "ldap_session_ttl",
            sa.Integer(),
            server_default="-1",
            nullable=False,
        ),
    )
    op.add_column(
        "Policies",
        sa.Column(
            "http_session_ttl",
            sa.Integer(),
            server_default="28800",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "group_policy_uc", "GroupAccessPolicyMemberships", type_="unique"
    )

    op.drop_column("Policies", "http_session_ttl")
    op.drop_column("Policies", "ldap_session_ttl")
    # ### end Alembic commands ###
