"""Merge migrations alembic head.

Revision ID: 692ae64e0cc5
Revises: 4334e2e871a4
Create Date: 2025-02-24 10:46:08.830692

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "692ae64e0cc5"
down_revision = "4334e2e871a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "group_policy_uc",
        "GroupAccessPolicyMemberships",
        ["group_id", "policy_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "group_policy_uc",
        "GroupAccessPolicyMemberships",
        type_="unique",
    )
    # ### end Alembic commands ###
