"""empty message

Revision ID: 6c858cc05da7
Revises: 56082d7ac0d4
Create Date: 2025-12-19 17:26:02.630201

"""
from alembic import op
import sqlalchemy as sa
from dishka import AsyncContainer


# revision identifiers, used by Alembic.
revision: None | str = '6c858cc05da7'
down_revision: None | str = '56082d7ac0d4'
branch_labels: None | list[str] = None
depends_on: None | list[str] = None


def upgrade(container: AsyncContainer) -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(container: AsyncContainer) -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
