"""empty message

Revision ID: 7cf914aeb510
Revises: d5272e9889c5
Create Date: 2023-10-17 13:12:58.885020

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cf914aeb510'
down_revision = 'd5272e9889c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('netmasks', postgresql.ARRAY(postgresql.CIDR()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('mfa_status', sa.Enum('DISABLED', 'ENABLED', 'WHITELIST', name='mfaflags'), server_default='DISABLED', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('priority', deferrable='True', initially='DEFERRED', name='priority_uc')
    )
    op.create_index(op.f('ix_Policies_netmasks'), 'Policies', ['netmasks'], unique=True)
    op.create_table('PolicyMFAMemberships',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['Policies.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'policy_id')
    )
    op.create_table('PolicyMemberships',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Groups.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['Policies.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'policy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PolicyMemberships')
    op.drop_table('PolicyMFAMemberships')
    op.drop_index(op.f('ix_Policies_netmasks'), table_name='Policies')
    op.drop_table('Policies')
    # ### end Alembic commands ###
