"""Modify LDAP schema.

Revision ID: b6cb962ecfac
Revises: 275222846605
Create Date: 2025-03-21 09:45:59.460969

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b6cb962ecfac"
down_revision = "275222846605"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "AttributeTypes", ["oid"])
    op.create_unique_constraint(None, "ObjectClasses", ["oid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ObjectClasses", type_="unique")
    op.drop_constraint(None, "AttributeTypes", type_="unique")
    # ### end Alembic commands ###
