"""depth

Revision ID: d4efa729315c
Revises: e8dedbdc7c70
Create Date: 2022-12-27 10:38:38.113394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4efa729315c'
down_revision = 'e8dedbdc7c70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Directory', sa.Column('depth', sa.Integer(), nullable=True))
    op.drop_column('Directory', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Directory', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Directory', 'depth')
    # ### end Alembic commands ###
