"""mail

Revision ID: fcb9c7819d74
Revises: ce220c6a2981
Create Date: 2023-01-27 06:01:20.306135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb9c7819d74'
down_revision = 'ce220c6a2981'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('mail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'mail')
    # ### end Alembic commands ###
