"""empty message

Revision ID: feb08b8e21ac
Revises: 9fc1aad1b5d0
Create Date: 2024-04-04 10:58:26.113100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb08b8e21ac'
down_revision = '9fc1aad1b5d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Attributes', sa.Column('bvalue', sa.LargeBinary(), nullable=True))
    op.alter_column('Attributes', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Attributes', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Attributes', 'bvalue')
    # ### end Alembic commands ###
