"""Enums.

Copyright (c) 2025 MultiFactor
License: https://github.com/MultiDirectoryLab/MultiDirectory/blob/main/LICENSE
"""

from enum import IntEnum, StrEnum


class AceType(IntEnum):
    """ACE types."""

    CREATE_CHILD = 1
    READ = 2
    WRITE = 3
    DELETE = 4
    PASSWORD_MODIFY = 5


class RoleScope(IntEnum):
    """Scope of the role."""

    BASE_OBJECT = 0
    SINGLE_LEVEL = 1
    WHOLE_SUBTREE = 2


class MFAFlags(IntEnum):
    """Two-Factor auth action."""

    DISABLED = 0
    ENABLED = 1
    WHITELIST = 2


class MFAChallengeStatuses(StrEnum):
    """Two-Factor challenge status."""

    BYPASS = "bypass"
    PENDING = "pending"


class KindType(StrEnum):
    """Object kind types."""

    STRUCTURAL = "STRUCTURAL"
    ABSTRACT = "ABSTRACT"
    AUXILIARY = "AUXILIARY"


class AuditSeverity(IntEnum):
    """Audit policy severity."""

    EMERGENCY = 0
    ALERT = 1
    CRITICAL = 2
    ERROR = 3
    WARNING = 4
    NOTICE = 5
    INFO = 6
    DEBUG = 7


class AuditDestinationProtocolType(StrEnum):
    """Audit destination protocol type."""

    UDP = "udp"
    TCP = "tcp"


class AuditDestinationServiceType(StrEnum):
    """Audit destination type."""

    SYSLOG = "syslog"


class ApiPermissionsType(IntEnum):
    """API Permissions."""

    PASSWORD_POLICY_GET_ALL = 1
    PASSWORD_POLICY_GET = 2
    PASSWORD_POLICY_GET_BY_DIR = 3
    PASSWORD_POLICY_UPDATE = 4
    PASSWORD_POLICY_RESET_DOMAIN_POLICY = 5
    PASSWORD_POLICY_TURNOFF = 6
    NETWORK_POLICY_CREATE = 7
    NETWORK_POLICY_GET_LIST_POLICIES = 8
    NETWORK_POLICY_DELETE = 9
    NETWORK_POLICY_SWITCH_NETWORK_POLICY = 10
    NETWORK_POLICY_SWAP_PRIORITIES = 11
    NETWORK_POLICY_UPDATE = 12
    DHCP_CHANGE_STATE = 13
    DHCP_GET_STATE = 14
    DHCP_CREATE_SUBNET = 15
    DHCP_DELETE_SUBNET = 16
    DHCP_GET_SUBNETS = 17
    DHCP_UPDATE_SUBNET = 18
    DHCP_CREATE_LEASE = 19
    DHCP_RELEASE_LEASE = 20
    DHCP_LIST_ACTIVE_LEASES = 21
    DHCP_FIND_LEASE = 22
    DHCP_LEASE_TO_RESERVATION = 23
    DHCP_ADD_RESERVATION = 24
    DHCP_GET_RESERVATIONS = 25
    DHCP_UPDATE_RESERVATION = 26
    DHCP_DELETE_RESERVATION = 27
    ATTRIBUTE_TYPE_GET = 28
    ATTRIBUTE_TYPE_CREATE = 29
    ATTRIBUTE_TYPE_GET_PAGINATOR = 30
    ATTRIBUTE_TYPE_UPDATE = 31
    ATTRIBUTE_TYPE_DELETE_ALL_BY_NAMES = 32
    ENTITY_TYPE_GET = 33
    ENTITY_TYPE_CREATE = 34
    ENTITY_TYPE_GET_PAGINATOR = 35
    ENTITY_TYPE_UPDATE = 36
    ENTITY_TYPE_DELETE_ALL_BY_NAMES = 37
    ENTITY_TYPE_GET_ATTRIBUTES = 38
    OBJECT_CLASS_GET = 39
    OBJECT_CLASS_CREATE = 40
    OBJECT_CLASS_GET_PAGINATOR = 41
    OBJECT_CLASS_UPDATE = 42
    OBJECT_CLASS_DELETE_ALL_BY_NAMES = 43
    DNS_SETUP_DNS = 44
    DNS_CREATE_RECORD = 45
    DNS_DELETE_RECORD = 46
    DNS_UPDATE_RECORD = 47
    DNS_GET_ALL_RECORDS = 48
    DNS_GET_DNS_STATUS = 49
    DNS_GET_ALL_ZONES_RECORDS = 50
    DNS_GET_FORWARD_ZONES = 51
    DNS_CREATE_ZONE = 52
    DNS_UPDATE_ZONE = 53
    DNS_DELETE_ZONE = 54
    DNS_CHECK_DNS_FORWARD_ZONE = 55
    DNS_RELOAD_ZONE = 56
    DNS_UPDATE_SERVER_OPTIONS = 57
    DNS_GET_SERVER_OPTIONS = 58
    DNS_RESTART_SERVER = 59
    KRB_SETUP_CATALOGUE = 60
    KRB_SETUP_KDC = 61
    KRB_KTADD = 62
    KRB_GET_STATUS = 63
    KRB_ADD_PRINCIPAL = 64
    KRB_RENAME_PRINCIPAL = 65
    KRB_RESET_PRINCIPAL_PW = 66
    KRB_DELETE_PRINCIPAL = 67
    AUDIT_GET_POLICIES = 68
    AUDIT_UPDATE_POLICY = 69
    AUDIT_GET_DESTINATIONS = 70
    AUDIT_CREATE_DESTINATION = 71
    AUDIT_DELETE_DESTINATION = 72
    AUDIT_UPDATE_DESTINATION = 73
    AUTH_RESET_PASSWORD = 74
    MFA_SETUP = 75
    MFA_REMOVE = 76
    MFA_GET = 77
    SESSION_GET_USER_SESSIONS = 78
    SESSION_CLEAR_USER_SESSIONS = 79
    SESSION_DELETE = 80
