"""Enums.

Copyright (c) 2025 MultiFactor
License: https://github.com/MultiDirectoryLab/MultiDirectory/blob/main/LICENSE
"""

from enum import UNIQUE, IntEnum, StrEnum, verify


class AceType(IntEnum):
    """ACE types."""

    CREATE_CHILD = 1
    READ = 2
    WRITE = 3
    DELETE = 4
    PASSWORD_MODIFY = 5


class RoleScope(IntEnum):
    """Scope of the role."""

    BASE_OBJECT = 0
    SINGLE_LEVEL = 1
    WHOLE_SUBTREE = 2


class MFAFlags(IntEnum):
    """Two-Factor auth action."""

    DISABLED = 0
    ENABLED = 1
    WHITELIST = 2


class MFAChallengeStatuses(StrEnum):
    """Two-Factor challenge status."""

    BYPASS = "bypass"
    PENDING = "pending"


class KindType(StrEnum):
    """Object kind types."""

    STRUCTURAL = "STRUCTURAL"
    ABSTRACT = "ABSTRACT"
    AUXILIARY = "AUXILIARY"


class AuditSeverity(IntEnum):
    """Audit policy severity."""

    EMERGENCY = 0
    ALERT = 1
    CRITICAL = 2
    ERROR = 3
    WARNING = 4
    NOTICE = 5
    INFO = 6
    DEBUG = 7


class AuditDestinationProtocolType(StrEnum):
    """Audit destination protocol type."""

    UDP = "udp"
    TCP = "tcp"


class AuditDestinationServiceType(StrEnum):
    """Audit destination type."""

    SYSLOG = "syslog"


@verify(UNIQUE)
class AuthoruzationRules(IntEnum):
    """API Permissions."""

    PASSWORD_POLICY_GET_ALL = 1
    PASSWORD_POLICY_GET = 2
    PASSWORD_POLICY_GET_BY_DIR = 3
    PASSWORD_POLICY_UPDATE = 4
    PASSWORD_POLICY_RESET_DOMAIN_POLICY = 5
    PASSWORD_BAN_WORD_GET_ALL = 6
    PASSWORD_BAN_WORD_REPLACE_ALL = 7
    NETWORK_POLICY_CREATE = 8
    NETWORK_POLICY_GET_LIST_POLICIES = 9
    NETWORK_POLICY_DELETE = 10
    NETWORK_POLICY_SWITCH_NETWORK_POLICY = 11
    NETWORK_POLICY_SWAP_PRIORITIES = 12
    NETWORK_POLICY_UPDATE = 13
    DHCP_CHANGE_STATE = 14
    DHCP_GET_STATE = 15
    DHCP_CREATE_SUBNET = 16
    DHCP_DELETE_SUBNET = 17
    DHCP_GET_SUBNETS = 18
    DHCP_UPDATE_SUBNET = 19
    DHCP_CREATE_LEASE = 20
    DHCP_RELEASE_LEASE = 21
    DHCP_LIST_ACTIVE_LEASES = 22
    DHCP_FIND_LEASE = 23
    DHCP_LEASE_TO_RESERVATION = 24
    DHCP_ADD_RESERVATION = 25
    DHCP_GET_RESERVATIONS = 26
    DHCP_UPDATE_RESERVATION = 27
    DHCP_DELETE_RESERVATION = 28
    ATTRIBUTE_TYPE_GET = 29
    ATTRIBUTE_TYPE_CREATE = 30
    ATTRIBUTE_TYPE_GET_PAGINATOR = 31
    ATTRIBUTE_TYPE_UPDATE = 32
    ATTRIBUTE_TYPE_DELETE_ALL_BY_NAMES = 33
    ENTITY_TYPE_GET = 34
    ENTITY_TYPE_CREATE = 35
    ENTITY_TYPE_GET_PAGINATOR = 36
    ENTITY_TYPE_UPDATE = 37
    ENTITY_TYPE_DELETE_ALL_BY_NAMES = 38
    ENTITY_TYPE_GET_ATTRIBUTES = 39
    OBJECT_CLASS_GET = 40
    OBJECT_CLASS_CREATE = 41
    OBJECT_CLASS_GET_PAGINATOR = 42
    OBJECT_CLASS_UPDATE = 43
    OBJECT_CLASS_DELETE_ALL_BY_NAMES = 44
    DNS_SETUP_DNS = 45
    DNS_CREATE_RECORD = 46
    DNS_DELETE_RECORD = 47
    DNS_UPDATE_RECORD = 48
    DNS_GET_ALL_RECORDS = 49
    DNS_GET_DNS_STATUS = 50
    DNS_GET_ALL_ZONES_RECORDS = 51
    DNS_GET_FORWARD_ZONES = 52
    DNS_CREATE_ZONE = 53
    DNS_UPDATE_ZONE = 54
    DNS_DELETE_ZONE = 55
    DNS_CHECK_DNS_FORWARD_ZONE = 56
    DNS_RELOAD_ZONE = 57
    DNS_UPDATE_SERVER_OPTIONS = 58
    DNS_GET_SERVER_OPTIONS = 59
    DNS_RESTART_SERVER = 60
    KRB_SETUP_CATALOGUE = 61
    KRB_SETUP_KDC = 62
    KRB_KTADD = 63
    KRB_GET_STATUS = 64
    KRB_ADD_PRINCIPAL = 65
    KRB_RENAME_PRINCIPAL = 66
    KRB_RESET_PRINCIPAL_PW = 67
    KRB_DELETE_PRINCIPAL = 68
    AUDIT_GET_POLICIES = 69
    AUDIT_UPDATE_POLICY = 70
    AUDIT_GET_DESTINATIONS = 71
    AUDIT_CREATE_DESTINATION = 72
    AUDIT_DELETE_DESTINATION = 73
    AUDIT_UPDATE_DESTINATION = 74
    AUTH_RESET_PASSWORD = 75
    MFA_SETUP = 76
    MFA_REMOVE = 77
    MFA_GET = 78
    SESSION_GET_USER_SESSIONS = 79
    SESSION_CLEAR_USER_SESSIONS = 80
    SESSION_DELETE = 81
