name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  REPO: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        run: |
          echo $TAG
          docker build -f app/Dockerfile . --tag $TAG --cache-from $TAG
          docker push $TAG
