name: build
on:
  push:
    branches: [main]

env:
  REPO: ${{ github.repository }}

jobs:
  build-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}_ssh_test:beta
          DOCKER_BUILDKIT: '1'
        run: |
          echo $TAG
          docker build integration_tests/ssh --tag $TAG --cache-from $TAG --build-arg BUILDKIT_INLINE_CACHE=1
          docker push $TAG

  build-tests:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}_test:beta
          DOCKER_BUILDKIT: '1'
        run: |
          echo $TAG
          docker build --push --target=runtime -f .docker/test.Dockerfile . -t $TAG --cache-to type=gha,mode=max --cache-from $TAG --build-arg BUILDKIT_INLINE_CACHE=1


  run-ssh-test:
    runs-on: ubuntu-latest
    needs: [build-tests, build-ssh]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull tests
        run: cd integration_tests/ssh && docker compose pull
      - name: run test enviroment
        run: cd integration_tests/ssh && docker compose up -d
      - name: run ssh test
        run: cd integration_tests/ssh && ./run.sh
      - name: shutdown test enviroment
        run: cd integration_tests/ssh && docker compose up -d

  run-tests:
    runs-on: ubuntu-latest
    needs: build-tests
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull tests
        env:
          TAG: ghcr.io/${{ env.REPO }}_test:beta
        run: docker compose -f docker-compose.remote.test.yml pull
      - name: Run tests
        env:
          TAG: ghcr.io/${{ env.REPO }}_test:beta
        run: docker compose -f docker-compose.remote.test.yml up --no-log-prefix --attach md-test
      - name: Teardown tests
        env:
          TAG: ghcr.io/${{ env.REPO }}_test:beta
        run: docker compose -f docker-compose.remote.test.yml down

  build-app:
    runs-on: ubuntu-latest
    needs: [build-tests, run-ssh-test, run-tests]
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}:beta
          DOCKER_BUILDKIT: '1'
        run: |
          echo $TAG
          echo $TAG2
          docker build --push --target=runtime -f .docker/Dockerfile . -t $TAG --cache-to type=gha,mode=max --cache-from $TAG --build-arg BUILDKIT_INLINE_CACHE=1

  build-kerberos:
    runs-on: ubuntu-latest
    needs: [build-tests, run-ssh-test, run-tests]
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}_kerberos:beta
          DOCKER_BUILDKIT: '1'
        run: |
          echo $TAG
          docker build --push --target=runtime -f .docker/krb.Dockerfile . -t $TAG --cache-to type=gha,mode=max --cache-from $TAG --build-arg BUILDKIT_INLINE_CACHE=1
