name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker build -f app/Dockerfile . --tag ghcr.io/multifactor/multidirectory:latest
          docker push ghcr.io/multifactor/multidirectory:latest
