name: build
on:
  push:
    branches:
      - main

env:
  REPO: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        env:
          TAG: ghcr.io/${{ env.REPO }}:latest
          DOCKER_BUILDKIT: 1
        run: |
          echo $TAG
          docker build -f app/Dockerfile . --tag $TAG --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $TAG
          docker push $TAG
