name: process_pull_request
on:
  push:
    branches: [main]
  pull_request: null

env:
  REPO: ${{ github.repository }}

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/lint.Dockerfile
          cache-from: type=gha
          tags: ghcr.io/${{ env.REPO }}_linters:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        run: docker run ghcr.io/${{ env.REPO }}_linters:latest ruff check

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/lint.Dockerfile
          cache-from: type=gha
          tags: ghcr.io/${{ env.REPO }}_linters:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull: true
      - name: Run linters
        run: docker run ghcr.io/${{ env.REPO }}_linters:latest flake8

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/lint.Dockerfile
          cache-from: type=gha
          tags: ghcr.io/${{ env.REPO }}_linters:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linters
        run: docker run ghcr.io/${{ env.REPO }}_linters:latest mypy .


